import { ATTRIBUTE_NAMES } from '../game/constants.js';

export default function Card({ card, index, selectedRole, candidate, preview = false, animation, onSelect, onPreviewAdd, disabled }) {
  const isSource = animation?.type === 'add' && animation.phase === 'source' && animation.indexes.includes(index);
  const isCreated = animation?.type === 'add' && animation.phase === 'created' && animation.targetIndex === index;
  const isCompress = ['process', 'absorb'].includes(animation?.type) && animation.phase === 'compress' && animation.indexes.includes(index);
  const isExit = animation?.type === 'process' && animation.phase === 'exit' && animation.exiting.includes(index);
  const isSettle = animation?.phase === 'settle' && (animation.indexes.includes(index) || animation.targetIndex === index);
  const classes = ['board-piece', `board-piece--${card.attribute}`, preview ? 'board-piece--preview' : '', selectedRole ? 'board-piece--selected' : '', candidate?.add ? 'board-piece--combine-candidate' : '', candidate?.process ? 'board-piece--reduce-candidate' : '', candidate?.absorb ? 'board-piece--absorb-candidate' : '', isSource ? 'board-piece--combine-source' : '', isCompress ? 'board-piece--reduce-compress' : '', isExit ? 'board-piece--reduce-auto-exit' : '', isSettle ? (animation.type === 'absorb' ? 'board-piece--absorb-settle' : 'board-piece--reduce-settle') : ''].filter(Boolean).join(' ');
  const source = card.parentSnapshot?.length === 2 ? card.parentSnapshot.map((parent) => `${ATTRIBUTE_NAMES[parent.attribute]}${parent.value}`).join(' + ') : '原生';
  const content = <><span className="board-piece-type-bar" /><strong className="board-piece-number">{card.value}</strong><span className="board-piece-attribute">{ATTRIBUTE_NAMES[card.attribute]}</span><small className="board-piece-source">{source}</small>{Boolean(selectedRole) && <><span className="board-piece-selection-role">{selectedRole === 1 ? '主卡' : '第二张'}</span><span className="board-piece-selected-ring" /></>}{(candidate?.add || candidate?.process || candidate?.absorb) && <span className="candidate-markers">{candidate.add && <i className="marker-add">＋</i>}{candidate.process && <i className="marker-process">÷</i>}{candidate.absorb && <i className="marker-absorb">◉</i>}</span>}</>;
  return <div className={`board-piece-wrapper ${preview ? 'board-piece-wrapper--preview' : ''} ${isCreated ? 'board-piece-wrapper--created' : ''}`}>{preview ? <button type="button" className={classes} disabled={disabled} aria-label={`即将相加，生成${ATTRIBUTE_NAMES[card.attribute]} ${card.value}`} onClick={(event) => { event.stopPropagation(); onPreviewAdd?.(); }}>{content}<span className="board-preview-action">即将相加 +{card.value}</span></button> : <button className={classes} onClick={onSelect} disabled={disabled} aria-label={`${ATTRIBUTE_NAMES[card.attribute]} ${card.value}`}>{content}</button>}</div>;
}
